/*
 * C# TWS API Client
 *
 * Copyright (C) 2013-2026  Interactive Brokers LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

using System.Collections.Generic;

namespace IBApi
{
    /**
     * @class CommissionAndFeesReport
     * @brief class representing the commission and fees generated by an execution.
     * @sa Execution
     */
    public class CommissionAndFeesReport
    {
        /**
        * @brief the execution's id this commission and fees belongs to.
        */
        public string ExecId { get; set; }

        /**
         * @brief the commission and fees cost.
         */
        public double CommissionAndFees { get; set; }

        /**
        * @brief the reporting currency.
        */
        public string Currency { get; set; }

        /**
        * @brief the realized profit and loss
        */
        public double RealizedPNL { get; set; }

        /**
         * @brief The income return.
         */
        public double Yield { get; set; }

        /**
         * @brief date expressed in yyyymmdd format.
         */
        public int YieldRedemptionDate { get; set; }

        public CommissionAndFeesReport()
        {
            CommissionAndFees = 0;
            RealizedPNL = 0;
            Yield = 0;
            YieldRedemptionDate = 0;
        }

        public override bool Equals(object p_other)
        {
            bool l_bRetVal;

            if (!(p_other is CommissionAndFeesReport l_theOther))
            {
                l_bRetVal = false;
            }
            else if (this == p_other)
            {
                l_bRetVal = true;
            }
            else
            {
                l_bRetVal = ExecId.Equals(l_theOther.ExecId, System.StringComparison.Ordinal);
            }
            return l_bRetVal;
        }

        public override int GetHashCode()
        {
            var hashCode = 662669467;
            hashCode *= -1521134295 + EqualityComparer<string>.Default.GetHashCode(ExecId);
            hashCode *= -1521134295 + CommissionAndFees.GetHashCode();
            hashCode *= -1521134295 + EqualityComparer<string>.Default.GetHashCode(Currency);
            hashCode *= -1521134295 + RealizedPNL.GetHashCode();
            hashCode *= -1521134295 + Yield.GetHashCode();
            hashCode *= -1521134295 + YieldRedemptionDate.GetHashCode();
            return hashCode;
        }
    }
}
