/*
 * C# TWS API Client
 *
 * Copyright (C) 2013-2026  Interactive Brokers LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AttachedOrders.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IBApi.protobuf {

  /// <summary>Holder for reflection information generated from AttachedOrders.proto</summary>
  public static partial class AttachedOrdersReflection {

    #region Descriptor
    /// <summary>File descriptor for AttachedOrders.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AttachedOrdersReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRBdHRhY2hlZE9yZGVycy5wcm90bxIIcHJvdG9idWYisAEKDkF0dGFjaGVk",
            "T3JkZXJzEhYKCXNsT3JkZXJJZBgBIAEoBUgAiAEBEhgKC3NsT3JkZXJUeXBl",
            "GAIgASgJSAGIAQESFgoJcHRPcmRlcklkGAMgASgFSAKIAQESGAoLcHRPcmRl",
            "clR5cGUYBCABKAlIA4gBAUIMCgpfc2xPcmRlcklkQg4KDF9zbE9yZGVyVHlw",
            "ZUIMCgpfcHRPcmRlcklkQg4KDF9wdE9yZGVyVHlwZUI+ChZjb20uaWIuY2xp",
            "ZW50LnByb3RvYnVmQhNBdHRhY2hlZE9yZGVyc1Byb3RvqgIOSUJBcGkucHJv",
            "dG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::IBApi.protobuf.AttachedOrders), global::IBApi.protobuf.AttachedOrders.Parser, new[]{ "SlOrderId", "SlOrderType", "PtOrderId", "PtOrderType" }, new[]{ "SlOrderId", "SlOrderType", "PtOrderId", "PtOrderType" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AttachedOrders : pb::IMessage<AttachedOrders>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AttachedOrders> _parser = new pb::MessageParser<AttachedOrders>(() => new AttachedOrders());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AttachedOrders> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IBApi.protobuf.AttachedOrdersReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttachedOrders() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttachedOrders(AttachedOrders other) : this() {
      _hasBits0 = other._hasBits0;
      slOrderId_ = other.slOrderId_;
      slOrderType_ = other.slOrderType_;
      ptOrderId_ = other.ptOrderId_;
      ptOrderType_ = other.ptOrderType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttachedOrders Clone() {
      return new AttachedOrders(this);
    }

    /// <summary>Field number for the "slOrderId" field.</summary>
    public const int SlOrderIdFieldNumber = 1;
    private readonly static int SlOrderIdDefaultValue = 0;

    private int slOrderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SlOrderId {
      get { if ((_hasBits0 & 1) != 0) { return slOrderId_; } else { return SlOrderIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        slOrderId_ = value;
      }
    }
    /// <summary>Gets whether the "slOrderId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSlOrderId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "slOrderId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSlOrderId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "slOrderType" field.</summary>
    public const int SlOrderTypeFieldNumber = 2;
    private readonly static string SlOrderTypeDefaultValue = "";

    private string slOrderType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SlOrderType {
      get { return slOrderType_ ?? SlOrderTypeDefaultValue; }
      set {
        slOrderType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "slOrderType" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSlOrderType {
      get { return slOrderType_ != null; }
    }
    /// <summary>Clears the value of the "slOrderType" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSlOrderType() {
      slOrderType_ = null;
    }

    /// <summary>Field number for the "ptOrderId" field.</summary>
    public const int PtOrderIdFieldNumber = 3;
    private readonly static int PtOrderIdDefaultValue = 0;

    private int ptOrderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PtOrderId {
      get { if ((_hasBits0 & 2) != 0) { return ptOrderId_; } else { return PtOrderIdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        ptOrderId_ = value;
      }
    }
    /// <summary>Gets whether the "ptOrderId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPtOrderId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "ptOrderId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPtOrderId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "ptOrderType" field.</summary>
    public const int PtOrderTypeFieldNumber = 4;
    private readonly static string PtOrderTypeDefaultValue = "";

    private string ptOrderType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PtOrderType {
      get { return ptOrderType_ ?? PtOrderTypeDefaultValue; }
      set {
        ptOrderType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "ptOrderType" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPtOrderType {
      get { return ptOrderType_ != null; }
    }
    /// <summary>Clears the value of the "ptOrderType" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPtOrderType() {
      ptOrderType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AttachedOrders);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AttachedOrders other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SlOrderId != other.SlOrderId) return false;
      if (SlOrderType != other.SlOrderType) return false;
      if (PtOrderId != other.PtOrderId) return false;
      if (PtOrderType != other.PtOrderType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasSlOrderId) hash ^= SlOrderId.GetHashCode();
      if (HasSlOrderType) hash ^= SlOrderType.GetHashCode();
      if (HasPtOrderId) hash ^= PtOrderId.GetHashCode();
      if (HasPtOrderType) hash ^= PtOrderType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasSlOrderId) {
        output.WriteRawTag(8);
        output.WriteInt32(SlOrderId);
      }
      if (HasSlOrderType) {
        output.WriteRawTag(18);
        output.WriteString(SlOrderType);
      }
      if (HasPtOrderId) {
        output.WriteRawTag(24);
        output.WriteInt32(PtOrderId);
      }
      if (HasPtOrderType) {
        output.WriteRawTag(34);
        output.WriteString(PtOrderType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasSlOrderId) {
        output.WriteRawTag(8);
        output.WriteInt32(SlOrderId);
      }
      if (HasSlOrderType) {
        output.WriteRawTag(18);
        output.WriteString(SlOrderType);
      }
      if (HasPtOrderId) {
        output.WriteRawTag(24);
        output.WriteInt32(PtOrderId);
      }
      if (HasPtOrderType) {
        output.WriteRawTag(34);
        output.WriteString(PtOrderType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasSlOrderId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SlOrderId);
      }
      if (HasSlOrderType) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SlOrderType);
      }
      if (HasPtOrderId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PtOrderId);
      }
      if (HasPtOrderType) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PtOrderType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AttachedOrders other) {
      if (other == null) {
        return;
      }
      if (other.HasSlOrderId) {
        SlOrderId = other.SlOrderId;
      }
      if (other.HasSlOrderType) {
        SlOrderType = other.SlOrderType;
      }
      if (other.HasPtOrderId) {
        PtOrderId = other.PtOrderId;
      }
      if (other.HasPtOrderType) {
        PtOrderType = other.PtOrderType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SlOrderId = input.ReadInt32();
            break;
          }
          case 18: {
            SlOrderType = input.ReadString();
            break;
          }
          case 24: {
            PtOrderId = input.ReadInt32();
            break;
          }
          case 34: {
            PtOrderType = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SlOrderId = input.ReadInt32();
            break;
          }
          case 18: {
            SlOrderType = input.ReadString();
            break;
          }
          case 24: {
            PtOrderId = input.ReadInt32();
            break;
          }
          case 34: {
            PtOrderType = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
