/*
 * C# TWS API Client
 *
 * Copyright (C) 2013-2026  Interactive Brokers LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HistoricalNewsRequest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IBApi.protobuf {

  /// <summary>Holder for reflection information generated from HistoricalNewsRequest.proto</summary>
  public static partial class HistoricalNewsRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for HistoricalNewsRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HistoricalNewsRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtIaXN0b3JpY2FsTmV3c1JlcXVlc3QucHJvdG8SCHByb3RvYnVmIp4DChVI",
            "aXN0b3JpY2FsTmV3c1JlcXVlc3QSEgoFcmVxSWQYASABKAVIAIgBARISCgVj",
            "b25JZBgCIAEoBUgBiAEBEhoKDXByb3ZpZGVyQ29kZXMYAyABKAlIAogBARIa",
            "Cg1zdGFydERhdGVUaW1lGAQgASgJSAOIAQESGAoLZW5kRGF0ZVRpbWUYBSAB",
            "KAlIBIgBARIZCgx0b3RhbFJlc3VsdHMYBiABKAVIBYgBARJZChVoaXN0b3Jp",
            "Y2FsTmV3c09wdGlvbnMYByADKAsyOi5wcm90b2J1Zi5IaXN0b3JpY2FsTmV3",
            "c1JlcXVlc3QuSGlzdG9yaWNhbE5ld3NPcHRpb25zRW50cnkaPAoaSGlzdG9y",
            "aWNhbE5ld3NPcHRpb25zRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIg",
            "ASgJOgI4AUIICgZfcmVxSWRCCAoGX2NvbklkQhAKDl9wcm92aWRlckNvZGVz",
            "QhAKDl9zdGFydERhdGVUaW1lQg4KDF9lbmREYXRlVGltZUIPCg1fdG90YWxS",
            "ZXN1bHRzQkUKFmNvbS5pYi5jbGllbnQucHJvdG9idWZCGkhpc3RvcmljYWxO",
            "ZXdzUmVxdWVzdFByb3RvqgIOSUJBcGkucHJvdG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::IBApi.protobuf.HistoricalNewsRequest), global::IBApi.protobuf.HistoricalNewsRequest.Parser, new[]{ "ReqId", "ConId", "ProviderCodes", "StartDateTime", "EndDateTime", "TotalResults", "HistoricalNewsOptions" }, new[]{ "ReqId", "ConId", "ProviderCodes", "StartDateTime", "EndDateTime", "TotalResults" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HistoricalNewsRequest : pb::IMessage<HistoricalNewsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HistoricalNewsRequest> _parser = new pb::MessageParser<HistoricalNewsRequest>(() => new HistoricalNewsRequest());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HistoricalNewsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IBApi.protobuf.HistoricalNewsRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HistoricalNewsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HistoricalNewsRequest(HistoricalNewsRequest other) : this() {
      _hasBits0 = other._hasBits0;
      reqId_ = other.reqId_;
      conId_ = other.conId_;
      providerCodes_ = other.providerCodes_;
      startDateTime_ = other.startDateTime_;
      endDateTime_ = other.endDateTime_;
      totalResults_ = other.totalResults_;
      historicalNewsOptions_ = other.historicalNewsOptions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HistoricalNewsRequest Clone() {
      return new HistoricalNewsRequest(this);
    }

    /// <summary>Field number for the "reqId" field.</summary>
    public const int ReqIdFieldNumber = 1;
    private readonly static int ReqIdDefaultValue = 0;

    private int reqId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ReqId {
      get { if ((_hasBits0 & 1) != 0) { return reqId_; } else { return ReqIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        reqId_ = value;
      }
    }
    /// <summary>Gets whether the "reqId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasReqId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "reqId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearReqId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "conId" field.</summary>
    public const int ConIdFieldNumber = 2;
    private readonly static int ConIdDefaultValue = 0;

    private int conId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ConId {
      get { if ((_hasBits0 & 2) != 0) { return conId_; } else { return ConIdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        conId_ = value;
      }
    }
    /// <summary>Gets whether the "conId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasConId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "conId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearConId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "providerCodes" field.</summary>
    public const int ProviderCodesFieldNumber = 3;
    private readonly static string ProviderCodesDefaultValue = "";

    private string providerCodes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProviderCodes {
      get { return providerCodes_ ?? ProviderCodesDefaultValue; }
      set {
        providerCodes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "providerCodes" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasProviderCodes {
      get { return providerCodes_ != null; }
    }
    /// <summary>Clears the value of the "providerCodes" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearProviderCodes() {
      providerCodes_ = null;
    }

    /// <summary>Field number for the "startDateTime" field.</summary>
    public const int StartDateTimeFieldNumber = 4;
    private readonly static string StartDateTimeDefaultValue = "";

    private string startDateTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StartDateTime {
      get { return startDateTime_ ?? StartDateTimeDefaultValue; }
      set {
        startDateTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "startDateTime" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStartDateTime {
      get { return startDateTime_ != null; }
    }
    /// <summary>Clears the value of the "startDateTime" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStartDateTime() {
      startDateTime_ = null;
    }

    /// <summary>Field number for the "endDateTime" field.</summary>
    public const int EndDateTimeFieldNumber = 5;
    private readonly static string EndDateTimeDefaultValue = "";

    private string endDateTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EndDateTime {
      get { return endDateTime_ ?? EndDateTimeDefaultValue; }
      set {
        endDateTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "endDateTime" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEndDateTime {
      get { return endDateTime_ != null; }
    }
    /// <summary>Clears the value of the "endDateTime" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEndDateTime() {
      endDateTime_ = null;
    }

    /// <summary>Field number for the "totalResults" field.</summary>
    public const int TotalResultsFieldNumber = 6;
    private readonly static int TotalResultsDefaultValue = 0;

    private int totalResults_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TotalResults {
      get { if ((_hasBits0 & 4) != 0) { return totalResults_; } else { return TotalResultsDefaultValue; } }
      set {
        _hasBits0 |= 4;
        totalResults_ = value;
      }
    }
    /// <summary>Gets whether the "totalResults" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTotalResults {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "totalResults" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTotalResults() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "historicalNewsOptions" field.</summary>
    public const int HistoricalNewsOptionsFieldNumber = 7;
    private static readonly pbc::MapField<string, string>.Codec _map_historicalNewsOptions_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 58);
    private readonly pbc::MapField<string, string> historicalNewsOptions_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> HistoricalNewsOptions {
      get { return historicalNewsOptions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HistoricalNewsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HistoricalNewsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ReqId != other.ReqId) return false;
      if (ConId != other.ConId) return false;
      if (ProviderCodes != other.ProviderCodes) return false;
      if (StartDateTime != other.StartDateTime) return false;
      if (EndDateTime != other.EndDateTime) return false;
      if (TotalResults != other.TotalResults) return false;
      if (!HistoricalNewsOptions.Equals(other.HistoricalNewsOptions)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasReqId) hash ^= ReqId.GetHashCode();
      if (HasConId) hash ^= ConId.GetHashCode();
      if (HasProviderCodes) hash ^= ProviderCodes.GetHashCode();
      if (HasStartDateTime) hash ^= StartDateTime.GetHashCode();
      if (HasEndDateTime) hash ^= EndDateTime.GetHashCode();
      if (HasTotalResults) hash ^= TotalResults.GetHashCode();
      hash ^= HistoricalNewsOptions.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasReqId) {
        output.WriteRawTag(8);
        output.WriteInt32(ReqId);
      }
      if (HasConId) {
        output.WriteRawTag(16);
        output.WriteInt32(ConId);
      }
      if (HasProviderCodes) {
        output.WriteRawTag(26);
        output.WriteString(ProviderCodes);
      }
      if (HasStartDateTime) {
        output.WriteRawTag(34);
        output.WriteString(StartDateTime);
      }
      if (HasEndDateTime) {
        output.WriteRawTag(42);
        output.WriteString(EndDateTime);
      }
      if (HasTotalResults) {
        output.WriteRawTag(48);
        output.WriteInt32(TotalResults);
      }
      historicalNewsOptions_.WriteTo(output, _map_historicalNewsOptions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasReqId) {
        output.WriteRawTag(8);
        output.WriteInt32(ReqId);
      }
      if (HasConId) {
        output.WriteRawTag(16);
        output.WriteInt32(ConId);
      }
      if (HasProviderCodes) {
        output.WriteRawTag(26);
        output.WriteString(ProviderCodes);
      }
      if (HasStartDateTime) {
        output.WriteRawTag(34);
        output.WriteString(StartDateTime);
      }
      if (HasEndDateTime) {
        output.WriteRawTag(42);
        output.WriteString(EndDateTime);
      }
      if (HasTotalResults) {
        output.WriteRawTag(48);
        output.WriteInt32(TotalResults);
      }
      historicalNewsOptions_.WriteTo(ref output, _map_historicalNewsOptions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasReqId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReqId);
      }
      if (HasConId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConId);
      }
      if (HasProviderCodes) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProviderCodes);
      }
      if (HasStartDateTime) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StartDateTime);
      }
      if (HasEndDateTime) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EndDateTime);
      }
      if (HasTotalResults) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalResults);
      }
      size += historicalNewsOptions_.CalculateSize(_map_historicalNewsOptions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HistoricalNewsRequest other) {
      if (other == null) {
        return;
      }
      if (other.HasReqId) {
        ReqId = other.ReqId;
      }
      if (other.HasConId) {
        ConId = other.ConId;
      }
      if (other.HasProviderCodes) {
        ProviderCodes = other.ProviderCodes;
      }
      if (other.HasStartDateTime) {
        StartDateTime = other.StartDateTime;
      }
      if (other.HasEndDateTime) {
        EndDateTime = other.EndDateTime;
      }
      if (other.HasTotalResults) {
        TotalResults = other.TotalResults;
      }
      historicalNewsOptions_.MergeFrom(other.historicalNewsOptions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ReqId = input.ReadInt32();
            break;
          }
          case 16: {
            ConId = input.ReadInt32();
            break;
          }
          case 26: {
            ProviderCodes = input.ReadString();
            break;
          }
          case 34: {
            StartDateTime = input.ReadString();
            break;
          }
          case 42: {
            EndDateTime = input.ReadString();
            break;
          }
          case 48: {
            TotalResults = input.ReadInt32();
            break;
          }
          case 58: {
            historicalNewsOptions_.AddEntriesFrom(input, _map_historicalNewsOptions_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ReqId = input.ReadInt32();
            break;
          }
          case 16: {
            ConId = input.ReadInt32();
            break;
          }
          case 26: {
            ProviderCodes = input.ReadString();
            break;
          }
          case 34: {
            StartDateTime = input.ReadString();
            break;
          }
          case 42: {
            EndDateTime = input.ReadString();
            break;
          }
          case 48: {
            TotalResults = input.ReadInt32();
            break;
          }
          case 58: {
            historicalNewsOptions_.AddEntriesFrom(ref input, _map_historicalNewsOptions_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
