/*
 * C# TWS API Client
 *
 * Copyright (C) 2013-2026  Interactive Brokers LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LockAndExitConfig.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IBApi.protobuf {

  /// <summary>Holder for reflection information generated from LockAndExitConfig.proto</summary>
  public static partial class LockAndExitConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for LockAndExitConfig.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LockAndExitConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdMb2NrQW5kRXhpdENvbmZpZy5wcm90bxIIcHJvdG9idWYipwEKEUxvY2tB",
            "bmRFeGl0Q29uZmlnEhsKDmF1dG9Mb2dvZmZUaW1lGAEgASgJSACIAQESHQoQ",
            "YXV0b0xvZ29mZlBlcmlvZBgCIAEoCUgBiAEBEhsKDmF1dG9Mb2dvZmZUeXBl",
            "GAMgASgJSAKIAQFCEQoPX2F1dG9Mb2dvZmZUaW1lQhMKEV9hdXRvTG9nb2Zm",
            "UGVyaW9kQhEKD19hdXRvTG9nb2ZmVHlwZUJBChZjb20uaWIuY2xpZW50LnBy",
            "b3RvYnVmQhZMb2NrQW5kRXhpdENvbmZpZ1Byb3RvqgIOSUJBcGkucHJvdG9i",
            "dWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::IBApi.protobuf.LockAndExitConfig), global::IBApi.protobuf.LockAndExitConfig.Parser, new[]{ "AutoLogoffTime", "AutoLogoffPeriod", "AutoLogoffType" }, new[]{ "AutoLogoffTime", "AutoLogoffPeriod", "AutoLogoffType" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LockAndExitConfig : pb::IMessage<LockAndExitConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LockAndExitConfig> _parser = new pb::MessageParser<LockAndExitConfig>(() => new LockAndExitConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LockAndExitConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IBApi.protobuf.LockAndExitConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LockAndExitConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LockAndExitConfig(LockAndExitConfig other) : this() {
      autoLogoffTime_ = other.autoLogoffTime_;
      autoLogoffPeriod_ = other.autoLogoffPeriod_;
      autoLogoffType_ = other.autoLogoffType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LockAndExitConfig Clone() {
      return new LockAndExitConfig(this);
    }

    /// <summary>Field number for the "autoLogoffTime" field.</summary>
    public const int AutoLogoffTimeFieldNumber = 1;
    private readonly static string AutoLogoffTimeDefaultValue = "";

    private string autoLogoffTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AutoLogoffTime {
      get { return autoLogoffTime_ ?? AutoLogoffTimeDefaultValue; }
      set {
        autoLogoffTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "autoLogoffTime" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAutoLogoffTime {
      get { return autoLogoffTime_ != null; }
    }
    /// <summary>Clears the value of the "autoLogoffTime" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAutoLogoffTime() {
      autoLogoffTime_ = null;
    }

    /// <summary>Field number for the "autoLogoffPeriod" field.</summary>
    public const int AutoLogoffPeriodFieldNumber = 2;
    private readonly static string AutoLogoffPeriodDefaultValue = "";

    private string autoLogoffPeriod_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AutoLogoffPeriod {
      get { return autoLogoffPeriod_ ?? AutoLogoffPeriodDefaultValue; }
      set {
        autoLogoffPeriod_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "autoLogoffPeriod" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAutoLogoffPeriod {
      get { return autoLogoffPeriod_ != null; }
    }
    /// <summary>Clears the value of the "autoLogoffPeriod" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAutoLogoffPeriod() {
      autoLogoffPeriod_ = null;
    }

    /// <summary>Field number for the "autoLogoffType" field.</summary>
    public const int AutoLogoffTypeFieldNumber = 3;
    private readonly static string AutoLogoffTypeDefaultValue = "";

    private string autoLogoffType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AutoLogoffType {
      get { return autoLogoffType_ ?? AutoLogoffTypeDefaultValue; }
      set {
        autoLogoffType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "autoLogoffType" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAutoLogoffType {
      get { return autoLogoffType_ != null; }
    }
    /// <summary>Clears the value of the "autoLogoffType" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAutoLogoffType() {
      autoLogoffType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LockAndExitConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LockAndExitConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AutoLogoffTime != other.AutoLogoffTime) return false;
      if (AutoLogoffPeriod != other.AutoLogoffPeriod) return false;
      if (AutoLogoffType != other.AutoLogoffType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAutoLogoffTime) hash ^= AutoLogoffTime.GetHashCode();
      if (HasAutoLogoffPeriod) hash ^= AutoLogoffPeriod.GetHashCode();
      if (HasAutoLogoffType) hash ^= AutoLogoffType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAutoLogoffTime) {
        output.WriteRawTag(10);
        output.WriteString(AutoLogoffTime);
      }
      if (HasAutoLogoffPeriod) {
        output.WriteRawTag(18);
        output.WriteString(AutoLogoffPeriod);
      }
      if (HasAutoLogoffType) {
        output.WriteRawTag(26);
        output.WriteString(AutoLogoffType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAutoLogoffTime) {
        output.WriteRawTag(10);
        output.WriteString(AutoLogoffTime);
      }
      if (HasAutoLogoffPeriod) {
        output.WriteRawTag(18);
        output.WriteString(AutoLogoffPeriod);
      }
      if (HasAutoLogoffType) {
        output.WriteRawTag(26);
        output.WriteString(AutoLogoffType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAutoLogoffTime) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AutoLogoffTime);
      }
      if (HasAutoLogoffPeriod) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AutoLogoffPeriod);
      }
      if (HasAutoLogoffType) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AutoLogoffType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LockAndExitConfig other) {
      if (other == null) {
        return;
      }
      if (other.HasAutoLogoffTime) {
        AutoLogoffTime = other.AutoLogoffTime;
      }
      if (other.HasAutoLogoffPeriod) {
        AutoLogoffPeriod = other.AutoLogoffPeriod;
      }
      if (other.HasAutoLogoffType) {
        AutoLogoffType = other.AutoLogoffType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AutoLogoffTime = input.ReadString();
            break;
          }
          case 18: {
            AutoLogoffPeriod = input.ReadString();
            break;
          }
          case 26: {
            AutoLogoffType = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AutoLogoffTime = input.ReadString();
            break;
          }
          case 18: {
            AutoLogoffPeriod = input.ReadString();
            break;
          }
          case 26: {
            AutoLogoffType = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
