/*
 * C# TWS API Client
 *
 * Copyright (C) 2013-2026  Interactive Brokers LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MarketDepthData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IBApi.protobuf {

  /// <summary>Holder for reflection information generated from MarketDepthData.proto</summary>
  public static partial class MarketDepthDataReflection {

    #region Descriptor
    /// <summary>File descriptor for MarketDepthData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MarketDepthDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVNYXJrZXREZXB0aERhdGEucHJvdG8SCHByb3RvYnVmIocCCg9NYXJrZXRE",
            "ZXB0aERhdGESFQoIcG9zaXRpb24YASABKAVIAIgBARIWCglvcGVyYXRpb24Y",
            "AiABKAVIAYgBARIRCgRzaWRlGAMgASgFSAKIAQESEgoFcHJpY2UYBCABKAFI",
            "A4gBARIRCgRzaXplGAUgASgJSASIAQESGAoLbWFya2V0TWFrZXIYBiABKAlI",
            "BYgBARIZCgxpc1NtYXJ0RGVwdGgYByABKAhIBogBAUILCglfcG9zaXRpb25C",
            "DAoKX29wZXJhdGlvbkIHCgVfc2lkZUIICgZfcHJpY2VCBwoFX3NpemVCDgoM",
            "X21hcmtldE1ha2VyQg8KDV9pc1NtYXJ0RGVwdGhCPwoWY29tLmliLmNsaWVu",
            "dC5wcm90b2J1ZkIUTWFya2V0RGVwdGhEYXRhUHJvdG+qAg5JQkFwaS5wcm90",
            "b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::IBApi.protobuf.MarketDepthData), global::IBApi.protobuf.MarketDepthData.Parser, new[]{ "Position", "Operation", "Side", "Price", "Size", "MarketMaker", "IsSmartDepth" }, new[]{ "Position", "Operation", "Side", "Price", "Size", "MarketMaker", "IsSmartDepth" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MarketDepthData : pb::IMessage<MarketDepthData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MarketDepthData> _parser = new pb::MessageParser<MarketDepthData>(() => new MarketDepthData());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MarketDepthData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IBApi.protobuf.MarketDepthDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MarketDepthData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MarketDepthData(MarketDepthData other) : this() {
      _hasBits0 = other._hasBits0;
      position_ = other.position_;
      operation_ = other.operation_;
      side_ = other.side_;
      price_ = other.price_;
      size_ = other.size_;
      marketMaker_ = other.marketMaker_;
      isSmartDepth_ = other.isSmartDepth_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MarketDepthData Clone() {
      return new MarketDepthData(this);
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 1;
    private readonly static int PositionDefaultValue = 0;

    private int position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Position {
      get { if ((_hasBits0 & 1) != 0) { return position_; } else { return PositionDefaultValue; } }
      set {
        _hasBits0 |= 1;
        position_ = value;
      }
    }
    /// <summary>Gets whether the "position" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPosition {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "position" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPosition() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "operation" field.</summary>
    public const int OperationFieldNumber = 2;
    private readonly static int OperationDefaultValue = 0;

    private int operation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Operation {
      get { if ((_hasBits0 & 2) != 0) { return operation_; } else { return OperationDefaultValue; } }
      set {
        _hasBits0 |= 2;
        operation_ = value;
      }
    }
    /// <summary>Gets whether the "operation" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOperation {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "operation" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOperation() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "side" field.</summary>
    public const int SideFieldNumber = 3;
    private readonly static int SideDefaultValue = 0;

    private int side_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Side {
      get { if ((_hasBits0 & 4) != 0) { return side_; } else { return SideDefaultValue; } }
      set {
        _hasBits0 |= 4;
        side_ = value;
      }
    }
    /// <summary>Gets whether the "side" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSide {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "side" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSide() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 4;
    private readonly static double PriceDefaultValue = 0D;

    private double price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Price {
      get { if ((_hasBits0 & 8) != 0) { return price_; } else { return PriceDefaultValue; } }
      set {
        _hasBits0 |= 8;
        price_ = value;
      }
    }
    /// <summary>Gets whether the "price" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPrice {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "price" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPrice() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 5;
    private readonly static string SizeDefaultValue = "";

    private string size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Size {
      get { return size_ ?? SizeDefaultValue; }
      set {
        size_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "size" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSize {
      get { return size_ != null; }
    }
    /// <summary>Clears the value of the "size" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSize() {
      size_ = null;
    }

    /// <summary>Field number for the "marketMaker" field.</summary>
    public const int MarketMakerFieldNumber = 6;
    private readonly static string MarketMakerDefaultValue = "";

    private string marketMaker_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MarketMaker {
      get { return marketMaker_ ?? MarketMakerDefaultValue; }
      set {
        marketMaker_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "marketMaker" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMarketMaker {
      get { return marketMaker_ != null; }
    }
    /// <summary>Clears the value of the "marketMaker" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMarketMaker() {
      marketMaker_ = null;
    }

    /// <summary>Field number for the "isSmartDepth" field.</summary>
    public const int IsSmartDepthFieldNumber = 7;
    private readonly static bool IsSmartDepthDefaultValue = false;

    private bool isSmartDepth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsSmartDepth {
      get { if ((_hasBits0 & 16) != 0) { return isSmartDepth_; } else { return IsSmartDepthDefaultValue; } }
      set {
        _hasBits0 |= 16;
        isSmartDepth_ = value;
      }
    }
    /// <summary>Gets whether the "isSmartDepth" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIsSmartDepth {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "isSmartDepth" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIsSmartDepth() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MarketDepthData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MarketDepthData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Position != other.Position) return false;
      if (Operation != other.Operation) return false;
      if (Side != other.Side) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Price, other.Price)) return false;
      if (Size != other.Size) return false;
      if (MarketMaker != other.MarketMaker) return false;
      if (IsSmartDepth != other.IsSmartDepth) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPosition) hash ^= Position.GetHashCode();
      if (HasOperation) hash ^= Operation.GetHashCode();
      if (HasSide) hash ^= Side.GetHashCode();
      if (HasPrice) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Price);
      if (HasSize) hash ^= Size.GetHashCode();
      if (HasMarketMaker) hash ^= MarketMaker.GetHashCode();
      if (HasIsSmartDepth) hash ^= IsSmartDepth.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPosition) {
        output.WriteRawTag(8);
        output.WriteInt32(Position);
      }
      if (HasOperation) {
        output.WriteRawTag(16);
        output.WriteInt32(Operation);
      }
      if (HasSide) {
        output.WriteRawTag(24);
        output.WriteInt32(Side);
      }
      if (HasPrice) {
        output.WriteRawTag(33);
        output.WriteDouble(Price);
      }
      if (HasSize) {
        output.WriteRawTag(42);
        output.WriteString(Size);
      }
      if (HasMarketMaker) {
        output.WriteRawTag(50);
        output.WriteString(MarketMaker);
      }
      if (HasIsSmartDepth) {
        output.WriteRawTag(56);
        output.WriteBool(IsSmartDepth);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPosition) {
        output.WriteRawTag(8);
        output.WriteInt32(Position);
      }
      if (HasOperation) {
        output.WriteRawTag(16);
        output.WriteInt32(Operation);
      }
      if (HasSide) {
        output.WriteRawTag(24);
        output.WriteInt32(Side);
      }
      if (HasPrice) {
        output.WriteRawTag(33);
        output.WriteDouble(Price);
      }
      if (HasSize) {
        output.WriteRawTag(42);
        output.WriteString(Size);
      }
      if (HasMarketMaker) {
        output.WriteRawTag(50);
        output.WriteString(MarketMaker);
      }
      if (HasIsSmartDepth) {
        output.WriteRawTag(56);
        output.WriteBool(IsSmartDepth);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPosition) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Position);
      }
      if (HasOperation) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Operation);
      }
      if (HasSide) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Side);
      }
      if (HasPrice) {
        size += 1 + 8;
      }
      if (HasSize) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Size);
      }
      if (HasMarketMaker) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MarketMaker);
      }
      if (HasIsSmartDepth) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MarketDepthData other) {
      if (other == null) {
        return;
      }
      if (other.HasPosition) {
        Position = other.Position;
      }
      if (other.HasOperation) {
        Operation = other.Operation;
      }
      if (other.HasSide) {
        Side = other.Side;
      }
      if (other.HasPrice) {
        Price = other.Price;
      }
      if (other.HasSize) {
        Size = other.Size;
      }
      if (other.HasMarketMaker) {
        MarketMaker = other.MarketMaker;
      }
      if (other.HasIsSmartDepth) {
        IsSmartDepth = other.IsSmartDepth;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Position = input.ReadInt32();
            break;
          }
          case 16: {
            Operation = input.ReadInt32();
            break;
          }
          case 24: {
            Side = input.ReadInt32();
            break;
          }
          case 33: {
            Price = input.ReadDouble();
            break;
          }
          case 42: {
            Size = input.ReadString();
            break;
          }
          case 50: {
            MarketMaker = input.ReadString();
            break;
          }
          case 56: {
            IsSmartDepth = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Position = input.ReadInt32();
            break;
          }
          case 16: {
            Operation = input.ReadInt32();
            break;
          }
          case 24: {
            Side = input.ReadInt32();
            break;
          }
          case 33: {
            Price = input.ReadDouble();
            break;
          }
          case 42: {
            Size = input.ReadString();
            break;
          }
          case 50: {
            MarketMaker = input.ReadString();
            break;
          }
          case 56: {
            IsSmartDepth = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
