/*
 * C# TWS API Client
 *
 * Copyright (C) 2013-2026  Interactive Brokers LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OrderStatus.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IBApi.protobuf {

  /// <summary>Holder for reflection information generated from OrderStatus.proto</summary>
  public static partial class OrderStatusReflection {

    #region Descriptor
    /// <summary>File descriptor for OrderStatus.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OrderStatusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFPcmRlclN0YXR1cy5wcm90bxIIcHJvdG9idWYiowMKC09yZGVyU3RhdHVz",
            "EhQKB29yZGVySWQYASABKAVIAIgBARITCgZzdGF0dXMYAiABKAlIAYgBARIT",
            "CgZmaWxsZWQYAyABKAlIAogBARIWCglyZW1haW5pbmcYBCABKAlIA4gBARIZ",
            "CgxhdmdGaWxsUHJpY2UYBSABKAFIBIgBARITCgZwZXJtSWQYBiABKANIBYgB",
            "ARIVCghwYXJlbnRJZBgHIAEoBUgGiAEBEhoKDWxhc3RGaWxsUHJpY2UYCCAB",
            "KAFIB4gBARIVCghjbGllbnRJZBgJIAEoBUgIiAEBEhQKB3doeUhlbGQYCiAB",
            "KAlICYgBARIYCgtta3RDYXBQcmljZRgLIAEoAUgKiAEBQgoKCF9vcmRlcklk",
            "QgkKB19zdGF0dXNCCQoHX2ZpbGxlZEIMCgpfcmVtYWluaW5nQg8KDV9hdmdG",
            "aWxsUHJpY2VCCQoHX3Blcm1JZEILCglfcGFyZW50SWRCEAoOX2xhc3RGaWxs",
            "UHJpY2VCCwoJX2NsaWVudElkQgoKCF93aHlIZWxkQg4KDF9ta3RDYXBQcmlj",
            "ZUI7ChZjb20uaWIuY2xpZW50LnByb3RvYnVmQhBPcmRlclN0YXR1c1Byb3Rv",
            "qgIOSUJBcGkucHJvdG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::IBApi.protobuf.OrderStatus), global::IBApi.protobuf.OrderStatus.Parser, new[]{ "OrderId", "Status", "Filled", "Remaining", "AvgFillPrice", "PermId", "ParentId", "LastFillPrice", "ClientId", "WhyHeld", "MktCapPrice" }, new[]{ "OrderId", "Status", "Filled", "Remaining", "AvgFillPrice", "PermId", "ParentId", "LastFillPrice", "ClientId", "WhyHeld", "MktCapPrice" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OrderStatus : pb::IMessage<OrderStatus>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderStatus> _parser = new pb::MessageParser<OrderStatus>(() => new OrderStatus());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrderStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IBApi.protobuf.OrderStatusReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStatus(OrderStatus other) : this() {
      _hasBits0 = other._hasBits0;
      orderId_ = other.orderId_;
      status_ = other.status_;
      filled_ = other.filled_;
      remaining_ = other.remaining_;
      avgFillPrice_ = other.avgFillPrice_;
      permId_ = other.permId_;
      parentId_ = other.parentId_;
      lastFillPrice_ = other.lastFillPrice_;
      clientId_ = other.clientId_;
      whyHeld_ = other.whyHeld_;
      mktCapPrice_ = other.mktCapPrice_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderStatus Clone() {
      return new OrderStatus(this);
    }

    /// <summary>Field number for the "orderId" field.</summary>
    public const int OrderIdFieldNumber = 1;
    private readonly static int OrderIdDefaultValue = 0;

    private int orderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OrderId {
      get { if ((_hasBits0 & 1) != 0) { return orderId_; } else { return OrderIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        orderId_ = value;
      }
    }
    /// <summary>Gets whether the "orderId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOrderId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "orderId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOrderId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private readonly static string StatusDefaultValue = "";

    private string status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Status {
      get { return status_ ?? StatusDefaultValue; }
      set {
        status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "status" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStatus {
      get { return status_ != null; }
    }
    /// <summary>Clears the value of the "status" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStatus() {
      status_ = null;
    }

    /// <summary>Field number for the "filled" field.</summary>
    public const int FilledFieldNumber = 3;
    private readonly static string FilledDefaultValue = "";

    private string filled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Filled {
      get { return filled_ ?? FilledDefaultValue; }
      set {
        filled_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "filled" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFilled {
      get { return filled_ != null; }
    }
    /// <summary>Clears the value of the "filled" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFilled() {
      filled_ = null;
    }

    /// <summary>Field number for the "remaining" field.</summary>
    public const int RemainingFieldNumber = 4;
    private readonly static string RemainingDefaultValue = "";

    private string remaining_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Remaining {
      get { return remaining_ ?? RemainingDefaultValue; }
      set {
        remaining_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "remaining" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRemaining {
      get { return remaining_ != null; }
    }
    /// <summary>Clears the value of the "remaining" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRemaining() {
      remaining_ = null;
    }

    /// <summary>Field number for the "avgFillPrice" field.</summary>
    public const int AvgFillPriceFieldNumber = 5;
    private readonly static double AvgFillPriceDefaultValue = 0D;

    private double avgFillPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double AvgFillPrice {
      get { if ((_hasBits0 & 2) != 0) { return avgFillPrice_; } else { return AvgFillPriceDefaultValue; } }
      set {
        _hasBits0 |= 2;
        avgFillPrice_ = value;
      }
    }
    /// <summary>Gets whether the "avgFillPrice" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAvgFillPrice {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "avgFillPrice" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAvgFillPrice() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "permId" field.</summary>
    public const int PermIdFieldNumber = 6;
    private readonly static long PermIdDefaultValue = 0L;

    private long permId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PermId {
      get { if ((_hasBits0 & 4) != 0) { return permId_; } else { return PermIdDefaultValue; } }
      set {
        _hasBits0 |= 4;
        permId_ = value;
      }
    }
    /// <summary>Gets whether the "permId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPermId {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "permId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPermId() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "parentId" field.</summary>
    public const int ParentIdFieldNumber = 7;
    private readonly static int ParentIdDefaultValue = 0;

    private int parentId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ParentId {
      get { if ((_hasBits0 & 8) != 0) { return parentId_; } else { return ParentIdDefaultValue; } }
      set {
        _hasBits0 |= 8;
        parentId_ = value;
      }
    }
    /// <summary>Gets whether the "parentId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasParentId {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "parentId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearParentId() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "lastFillPrice" field.</summary>
    public const int LastFillPriceFieldNumber = 8;
    private readonly static double LastFillPriceDefaultValue = 0D;

    private double lastFillPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double LastFillPrice {
      get { if ((_hasBits0 & 16) != 0) { return lastFillPrice_; } else { return LastFillPriceDefaultValue; } }
      set {
        _hasBits0 |= 16;
        lastFillPrice_ = value;
      }
    }
    /// <summary>Gets whether the "lastFillPrice" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLastFillPrice {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "lastFillPrice" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLastFillPrice() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "clientId" field.</summary>
    public const int ClientIdFieldNumber = 9;
    private readonly static int ClientIdDefaultValue = 0;

    private int clientId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ClientId {
      get { if ((_hasBits0 & 32) != 0) { return clientId_; } else { return ClientIdDefaultValue; } }
      set {
        _hasBits0 |= 32;
        clientId_ = value;
      }
    }
    /// <summary>Gets whether the "clientId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasClientId {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "clientId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearClientId() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "whyHeld" field.</summary>
    public const int WhyHeldFieldNumber = 10;
    private readonly static string WhyHeldDefaultValue = "";

    private string whyHeld_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WhyHeld {
      get { return whyHeld_ ?? WhyHeldDefaultValue; }
      set {
        whyHeld_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "whyHeld" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasWhyHeld {
      get { return whyHeld_ != null; }
    }
    /// <summary>Clears the value of the "whyHeld" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearWhyHeld() {
      whyHeld_ = null;
    }

    /// <summary>Field number for the "mktCapPrice" field.</summary>
    public const int MktCapPriceFieldNumber = 11;
    private readonly static double MktCapPriceDefaultValue = 0D;

    private double mktCapPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double MktCapPrice {
      get { if ((_hasBits0 & 64) != 0) { return mktCapPrice_; } else { return MktCapPriceDefaultValue; } }
      set {
        _hasBits0 |= 64;
        mktCapPrice_ = value;
      }
    }
    /// <summary>Gets whether the "mktCapPrice" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMktCapPrice {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "mktCapPrice" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMktCapPrice() {
      _hasBits0 &= ~64;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrderStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrderStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderId != other.OrderId) return false;
      if (Status != other.Status) return false;
      if (Filled != other.Filled) return false;
      if (Remaining != other.Remaining) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(AvgFillPrice, other.AvgFillPrice)) return false;
      if (PermId != other.PermId) return false;
      if (ParentId != other.ParentId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LastFillPrice, other.LastFillPrice)) return false;
      if (ClientId != other.ClientId) return false;
      if (WhyHeld != other.WhyHeld) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MktCapPrice, other.MktCapPrice)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOrderId) hash ^= OrderId.GetHashCode();
      if (HasStatus) hash ^= Status.GetHashCode();
      if (HasFilled) hash ^= Filled.GetHashCode();
      if (HasRemaining) hash ^= Remaining.GetHashCode();
      if (HasAvgFillPrice) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(AvgFillPrice);
      if (HasPermId) hash ^= PermId.GetHashCode();
      if (HasParentId) hash ^= ParentId.GetHashCode();
      if (HasLastFillPrice) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LastFillPrice);
      if (HasClientId) hash ^= ClientId.GetHashCode();
      if (HasWhyHeld) hash ^= WhyHeld.GetHashCode();
      if (HasMktCapPrice) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MktCapPrice);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOrderId) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      if (HasStatus) {
        output.WriteRawTag(18);
        output.WriteString(Status);
      }
      if (HasFilled) {
        output.WriteRawTag(26);
        output.WriteString(Filled);
      }
      if (HasRemaining) {
        output.WriteRawTag(34);
        output.WriteString(Remaining);
      }
      if (HasAvgFillPrice) {
        output.WriteRawTag(41);
        output.WriteDouble(AvgFillPrice);
      }
      if (HasPermId) {
        output.WriteRawTag(48);
        output.WriteInt64(PermId);
      }
      if (HasParentId) {
        output.WriteRawTag(56);
        output.WriteInt32(ParentId);
      }
      if (HasLastFillPrice) {
        output.WriteRawTag(65);
        output.WriteDouble(LastFillPrice);
      }
      if (HasClientId) {
        output.WriteRawTag(72);
        output.WriteInt32(ClientId);
      }
      if (HasWhyHeld) {
        output.WriteRawTag(82);
        output.WriteString(WhyHeld);
      }
      if (HasMktCapPrice) {
        output.WriteRawTag(89);
        output.WriteDouble(MktCapPrice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOrderId) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      if (HasStatus) {
        output.WriteRawTag(18);
        output.WriteString(Status);
      }
      if (HasFilled) {
        output.WriteRawTag(26);
        output.WriteString(Filled);
      }
      if (HasRemaining) {
        output.WriteRawTag(34);
        output.WriteString(Remaining);
      }
      if (HasAvgFillPrice) {
        output.WriteRawTag(41);
        output.WriteDouble(AvgFillPrice);
      }
      if (HasPermId) {
        output.WriteRawTag(48);
        output.WriteInt64(PermId);
      }
      if (HasParentId) {
        output.WriteRawTag(56);
        output.WriteInt32(ParentId);
      }
      if (HasLastFillPrice) {
        output.WriteRawTag(65);
        output.WriteDouble(LastFillPrice);
      }
      if (HasClientId) {
        output.WriteRawTag(72);
        output.WriteInt32(ClientId);
      }
      if (HasWhyHeld) {
        output.WriteRawTag(82);
        output.WriteString(WhyHeld);
      }
      if (HasMktCapPrice) {
        output.WriteRawTag(89);
        output.WriteDouble(MktCapPrice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasOrderId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OrderId);
      }
      if (HasStatus) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
      }
      if (HasFilled) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Filled);
      }
      if (HasRemaining) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Remaining);
      }
      if (HasAvgFillPrice) {
        size += 1 + 8;
      }
      if (HasPermId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PermId);
      }
      if (HasParentId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ParentId);
      }
      if (HasLastFillPrice) {
        size += 1 + 8;
      }
      if (HasClientId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ClientId);
      }
      if (HasWhyHeld) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WhyHeld);
      }
      if (HasMktCapPrice) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrderStatus other) {
      if (other == null) {
        return;
      }
      if (other.HasOrderId) {
        OrderId = other.OrderId;
      }
      if (other.HasStatus) {
        Status = other.Status;
      }
      if (other.HasFilled) {
        Filled = other.Filled;
      }
      if (other.HasRemaining) {
        Remaining = other.Remaining;
      }
      if (other.HasAvgFillPrice) {
        AvgFillPrice = other.AvgFillPrice;
      }
      if (other.HasPermId) {
        PermId = other.PermId;
      }
      if (other.HasParentId) {
        ParentId = other.ParentId;
      }
      if (other.HasLastFillPrice) {
        LastFillPrice = other.LastFillPrice;
      }
      if (other.HasClientId) {
        ClientId = other.ClientId;
      }
      if (other.HasWhyHeld) {
        WhyHeld = other.WhyHeld;
      }
      if (other.HasMktCapPrice) {
        MktCapPrice = other.MktCapPrice;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
          case 18: {
            Status = input.ReadString();
            break;
          }
          case 26: {
            Filled = input.ReadString();
            break;
          }
          case 34: {
            Remaining = input.ReadString();
            break;
          }
          case 41: {
            AvgFillPrice = input.ReadDouble();
            break;
          }
          case 48: {
            PermId = input.ReadInt64();
            break;
          }
          case 56: {
            ParentId = input.ReadInt32();
            break;
          }
          case 65: {
            LastFillPrice = input.ReadDouble();
            break;
          }
          case 72: {
            ClientId = input.ReadInt32();
            break;
          }
          case 82: {
            WhyHeld = input.ReadString();
            break;
          }
          case 89: {
            MktCapPrice = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
          case 18: {
            Status = input.ReadString();
            break;
          }
          case 26: {
            Filled = input.ReadString();
            break;
          }
          case 34: {
            Remaining = input.ReadString();
            break;
          }
          case 41: {
            AvgFillPrice = input.ReadDouble();
            break;
          }
          case 48: {
            PermId = input.ReadInt64();
            break;
          }
          case 56: {
            ParentId = input.ReadInt32();
            break;
          }
          case 65: {
            LastFillPrice = input.ReadDouble();
            break;
          }
          case 72: {
            ClientId = input.ReadInt32();
            break;
          }
          case 82: {
            WhyHeld = input.ReadString();
            break;
          }
          case 89: {
            MktCapPrice = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
