/*
 * C# TWS API Client
 *
 * Copyright (C) 2013-2026  Interactive Brokers LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlaceOrderRequest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IBApi.protobuf {

  /// <summary>Holder for reflection information generated from PlaceOrderRequest.proto</summary>
  public static partial class PlaceOrderRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for PlaceOrderRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlaceOrderRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdQbGFjZU9yZGVyUmVxdWVzdC5wcm90bxIIcHJvdG9idWYaDkNvbnRyYWN0",
            "LnByb3RvGgtPcmRlci5wcm90bxoUQXR0YWNoZWRPcmRlcnMucHJvdG8i5gEK",
            "EVBsYWNlT3JkZXJSZXF1ZXN0EhQKB29yZGVySWQYASABKAVIAIgBARIpCghj",
            "b250cmFjdBgCIAEoCzISLnByb3RvYnVmLkNvbnRyYWN0SAGIAQESIwoFb3Jk",
            "ZXIYAyABKAsyDy5wcm90b2J1Zi5PcmRlckgCiAEBEjUKDmF0dGFjaGVkT3Jk",
            "ZXJzGAQgASgLMhgucHJvdG9idWYuQXR0YWNoZWRPcmRlcnNIA4gBAUIKCghf",
            "b3JkZXJJZEILCglfY29udHJhY3RCCAoGX29yZGVyQhEKD19hdHRhY2hlZE9y",
            "ZGVyc0JBChZjb20uaWIuY2xpZW50LnByb3RvYnVmQhZQbGFjZU9yZGVyUmVx",
            "dWVzdFByb3RvqgIOSUJBcGkucHJvdG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::IBApi.protobuf.ContractReflection.Descriptor, global::IBApi.protobuf.OrderReflection.Descriptor, global::IBApi.protobuf.AttachedOrdersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::IBApi.protobuf.PlaceOrderRequest), global::IBApi.protobuf.PlaceOrderRequest.Parser, new[]{ "OrderId", "Contract", "Order", "AttachedOrders" }, new[]{ "OrderId", "Contract", "Order", "AttachedOrders" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlaceOrderRequest : pb::IMessage<PlaceOrderRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlaceOrderRequest> _parser = new pb::MessageParser<PlaceOrderRequest>(() => new PlaceOrderRequest());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlaceOrderRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IBApi.protobuf.PlaceOrderRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlaceOrderRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlaceOrderRequest(PlaceOrderRequest other) : this() {
      _hasBits0 = other._hasBits0;
      orderId_ = other.orderId_;
      contract_ = other.contract_ != null ? other.contract_.Clone() : null;
      order_ = other.order_ != null ? other.order_.Clone() : null;
      attachedOrders_ = other.attachedOrders_ != null ? other.attachedOrders_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlaceOrderRequest Clone() {
      return new PlaceOrderRequest(this);
    }

    /// <summary>Field number for the "orderId" field.</summary>
    public const int OrderIdFieldNumber = 1;
    private readonly static int OrderIdDefaultValue = 0;

    private int orderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OrderId {
      get { if ((_hasBits0 & 1) != 0) { return orderId_; } else { return OrderIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        orderId_ = value;
      }
    }
    /// <summary>Gets whether the "orderId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOrderId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "orderId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOrderId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "contract" field.</summary>
    public const int ContractFieldNumber = 2;
    private global::IBApi.protobuf.Contract contract_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::IBApi.protobuf.Contract Contract {
      get { return contract_; }
      set {
        contract_ = value;
      }
    }

    /// <summary>Field number for the "order" field.</summary>
    public const int OrderFieldNumber = 3;
    private global::IBApi.protobuf.Order order_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::IBApi.protobuf.Order Order {
      get { return order_; }
      set {
        order_ = value;
      }
    }

    /// <summary>Field number for the "attachedOrders" field.</summary>
    public const int AttachedOrdersFieldNumber = 4;
    private global::IBApi.protobuf.AttachedOrders attachedOrders_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::IBApi.protobuf.AttachedOrders AttachedOrders {
      get { return attachedOrders_; }
      set {
        attachedOrders_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlaceOrderRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlaceOrderRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderId != other.OrderId) return false;
      if (!object.Equals(Contract, other.Contract)) return false;
      if (!object.Equals(Order, other.Order)) return false;
      if (!object.Equals(AttachedOrders, other.AttachedOrders)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOrderId) hash ^= OrderId.GetHashCode();
      if (contract_ != null) hash ^= Contract.GetHashCode();
      if (order_ != null) hash ^= Order.GetHashCode();
      if (attachedOrders_ != null) hash ^= AttachedOrders.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOrderId) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      if (contract_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Contract);
      }
      if (order_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Order);
      }
      if (attachedOrders_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(AttachedOrders);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOrderId) {
        output.WriteRawTag(8);
        output.WriteInt32(OrderId);
      }
      if (contract_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Contract);
      }
      if (order_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Order);
      }
      if (attachedOrders_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(AttachedOrders);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasOrderId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OrderId);
      }
      if (contract_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Contract);
      }
      if (order_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Order);
      }
      if (attachedOrders_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AttachedOrders);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlaceOrderRequest other) {
      if (other == null) {
        return;
      }
      if (other.HasOrderId) {
        OrderId = other.OrderId;
      }
      if (other.contract_ != null) {
        if (contract_ == null) {
          Contract = new global::IBApi.protobuf.Contract();
        }
        Contract.MergeFrom(other.Contract);
      }
      if (other.order_ != null) {
        if (order_ == null) {
          Order = new global::IBApi.protobuf.Order();
        }
        Order.MergeFrom(other.Order);
      }
      if (other.attachedOrders_ != null) {
        if (attachedOrders_ == null) {
          AttachedOrders = new global::IBApi.protobuf.AttachedOrders();
        }
        AttachedOrders.MergeFrom(other.AttachedOrders);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
          case 18: {
            if (contract_ == null) {
              Contract = new global::IBApi.protobuf.Contract();
            }
            input.ReadMessage(Contract);
            break;
          }
          case 26: {
            if (order_ == null) {
              Order = new global::IBApi.protobuf.Order();
            }
            input.ReadMessage(Order);
            break;
          }
          case 34: {
            if (attachedOrders_ == null) {
              AttachedOrders = new global::IBApi.protobuf.AttachedOrders();
            }
            input.ReadMessage(AttachedOrders);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OrderId = input.ReadInt32();
            break;
          }
          case 18: {
            if (contract_ == null) {
              Contract = new global::IBApi.protobuf.Contract();
            }
            input.ReadMessage(Contract);
            break;
          }
          case 26: {
            if (order_ == null) {
              Order = new global::IBApi.protobuf.Order();
            }
            input.ReadMessage(Order);
            break;
          }
          case 34: {
            if (attachedOrders_ == null) {
              AttachedOrders = new global::IBApi.protobuf.AttachedOrders();
            }
            input.ReadMessage(AttachedOrders);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
